# Generated by Django 2.2.2 on 2019-06-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('description', models.TextField()),
                ('other_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OtherField')),
            ],
        ),
    ]
